### ISSUE TITLE
Functionality/Technical Feedback

### ISSUE THREAD

**Issue by Gibson1080** [danifergu/Project-Respository#2]
The website loaded correctly and was able to get to the home page. It looks really good. I had an issue opening some of the links on your top navigation bar. Links "Home " and "Map" did not open the appropriate pages correctly, I would suggest you work on that as well. Your site map is created but given the problem with links, there is no coherent way of navigating through your website.Make sure to include the top navigation bar on all the pages

**Comment by danifergu** [comment]
Thank you for the comments!
