### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by Gibson1080** [danifergu/Project-Respository#3]
I noticed that though your pages show the information you want them to show, they don't have very good styling. The Foods page for example,.You could use flexbox to make the images appear more appealing to the eye.
<img width="1439" alt="Screen Shot 2022-11-11 at 2 28 47 PM" src="https://user-images.githubusercontent.com/112510165/201416094-c95ea8cf-16fb-45e9-8944-e64110c6fd57.png">

**Comment by danifergu** [comment]
Thank you!!
