### ISSUE TITLE
Peer Review - Ysbely Santos 

### ISSUE THREAD

**Issue by Ysbely** [danifergu/Project-Respository#4]
Hey Daniel!

Really loved the concept of your site, what a unique idea,

In terms of content, I would change some of the colors used. Since it is loud and flashy it does not give the vibe of a finance site. I would also center the “Submit” and “Reset” buttons on the survey page. Moreover, adding some background color and centering the feedback survey will make the page more neat. The pictures can be centered more and made more suitable to fit the page so the design is cohesive and looks more clear and structured.

Best,
Ysbely Santos

**Comment by danifergu** [comment]
Thank you so much for the review!!! It has been of great help.
